config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'

  root to: "songs#index"

  resources :songs do
    collection do
      get :find
    end
  end

  resources :users do
    collection do
      get :find
    end
  end
  
  resources :sessions

end

app/models/song.rb
class Song < ActiveRecord::Base

  has_and_belongs_to_many :users

  validates_uniqueness_of :soundcloud_id

end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :songs

  attr_accessor :password, :password_confirmation
  before_save :encrypt_password

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_confirmation_of :password # adds password_confirmation attribute
  validates_presence_of :password, :on => :create

# password length
# format of email address
# username


  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?


  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email],
                              params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = 'Successfuly Logged in!'
      redirect_to root_url
    else
      flash[:notice] = 'Invalid e-mail or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
    flash[:notice] = 'See you later!'
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  respond_to :html, :json

  skip_before_filter  :verify_authenticity_token

  def index
    session[:played_songs] = ''
  end

  def create
    liked_song = Song.find_by(soundcloud_id: song_params)
    session[:liked_song] = liked_song
    session[:counter] = -1
    if liked_song
      current_user.songs << liked_song unless current_user.songs.find_by(soundcloud_id: liked_song.soundcloud_id)
    else
      current_user.songs.create(soundcloud_id: song_params)
    end
    render json: { :success => true }
  end

  def find
    flag = true

    oldsong = Song.find_by(soundcloud_id: song_params)

    ordered_liked_songs = current_user.songs.sort_by {|song| song.created_at}

    if !oldsong && ordered_liked_songs
      oldsong = ordered_liked_songs.last
    elsif !oldsong
      flag = false
    end

    session[:played_songs] += (song_params.to_s + ',')

    if flag
      songarray = []
      session[:played_songs] += (song_params.to_s + ',')
      played_songs = session[:played_songs].split(',')
      count = Hash.new(0)
      oldsong_users = oldsong.users.where('id != ?', current_user.id).to_a
      oldsong_users_songs = oldsong_users.map{|user| user.songs}.flatten
      oldsong_users_songs_wo_old_song = oldsong_users_songs.reject{|song| played_songs.include?(song.soundcloud_id.to_s)}
      oldsong_users_songs_wo_old_song.each {|song| songarray << song}
      songarray.each {|song| count[song] +=1}
      @nextsong = count.sort_by {|k,v| v}.last
      render :json => { soundcloud_id: @nextsong[0].soundcloud_id }
    end
  end


  #
  #   oldsong = Song.find_by(soundcloud_id: song_params) if Song.find_by(soundcloud_id: song_params)
  #   liked_status = current_user.songs.exists?(oldsong)
  #   songarray = []
  #   count = Hash.new(0)
  #   oldsong_users = oldsong.users.where('id != ?', current_user.id).to_a
  #   oldsong_users_songs = oldsong_users.map{|user| user.songs}.flatten
  #   oldsong_users_songs_wo_old_song = oldsong_users_songs.reject{|song| (song.soundcloud_id == song_params.to_i)}
  #   oldsong_users_songs_wo_old_song.each {|song| songarray << song}
  #   songarray.each {|song| count[song] +=1}
  #   @nextsong = count.sort_by {|k,v| v}.last
  #   render :json => { soundcloud_id: @nextsong[0].soundcloud_id, liked_status: liked_status }
  # end



  private

  def song_params
    params.require(:soundcloud_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :json

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
      flash[:notice] = "Welcome to Selecta"
    else
      render "new"
    end
  end

  def find
    user = User.find(params[:user])
    @songs = user.songs
    render :json => { songs: @songs }
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Selecta">
<head>
  <title>SelectaOfficial</title>
  <script src="https://connect.soundcloud.com/sdk.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<script type="text/ng-template" id="track.html">
  <div ng-controller="TrackController">
    <div class="player">
    <div class="container-fluid text-center">
    <div class="row">
      <h1>{{selected_song.title}}</h1>
      <img class="artwork" ng-src="{{ selected_song.artwork_url.replace('large','t500x500') }}"/>
      <div>
      <button class="btn btn-default" ng-click="skipBackward()" id='forwards'><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></button>
      <button class="btn btn-default" ng-click="skipForward()" id='backwards'><span class="glyphicon glyphicon-forward" aria-hidden="true"></span></button>
      </div>
      </br>
      <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" id="navbarTitle" href="/#/"></a>
          </div>
            <ul class="nav navbar-nav text-center playpausenextbuttons">
              <button class="btn btn-default" ng-click="play()" id='Play'><span class="glyphicon glyphicon-play" aria-hidden="true"></span></button>
              <button class="btn btn-default" ng-click="stop()" id='Pause'><span class="glyphicon glyphicon-pause" aria-hidden="true"></span></button>
              <button class="btn btn-default" ng-click="next()" id='Next'><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
              <button class="btn btn-default" ng-click="like()" id='Like'><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></button>
            </ul>
            <ul class="nav navbar-nav navbar-right volumeControl">
              <button class="btn btn-default" ng-click="mute()" id='Mute'><span class="glyphicon glyphicon-volume-off"></span></button>
              <button class="btn btn-default" ng-click="volumeDown()" id='volumeDown'><span class="glyphicon glyphicon-volume-down"></span></button>
              <button class="btn btn-default" ng-click="volumeUp()" id='volumeUp'><span class="glyphicon glyphicon-volume-up"></span></button>
            </ul>
          </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</script>

<script type="text/ng-template" id="home.html">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="logo text-center">
            <%= image_tag "selecta-logo.png" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="typer text-center">
          <h2 data-typer-targets="This is Music., Acoustic., Electronic., Soul., Jazz., Hip-Hop., Classical., Selecta Tune., Start Discovering...">Selecta.</h2>
          <script>
            $(function () {
              $('[data-typer-targets]').typer();
            });
          </script>
        </div>
      </div>
  </div>

</script>

<script type="text/ng-template" id="results.html"></script>

<script type="text/ng-template" id="likeHistory.html">
  <div class="results">
    <ul class="list-group" ng-repeat="like in likes">
      <li class="list-group-item">
        <a ng-href="#/track/{{like.id}}" >{{like.title}}</a>
      </li>
    </ul>
  </div>
</script>

<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<div ng-controller="SongSearchController">
  <div class="backgroundimageStyling">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" id="navbarTitle" href="/#/">Selecta</a>
        </div>
        <form class="nav navbar-form navbar-left">
          <div class="form-group">
            <input type="text" ng-model="searchTerm" name="searchstring" class="form-control" placeholder="Start discovering...">
          </div>
          <a ng-href="#/results"><button ng-click="doSearch()" type="submit" class="btn btn-default" id="find">Search</button></a>
        </form>
        <ul class="nav navbar-nav text-center currentSongButton">
          <span ng-controller="TrackController">
            <li><button id="currentSong" ng-click="currentSong()"class="btn btn-default"><span class="glyphicon glyphicon-music"></span></button></li>
          </span>
        </ul>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><a id="likeHistory" ng-href=<%="#/likeHistory/#{current_user.id}"%>>Like History</a></li>
              <li><%= link_to "Log out", log_out_path %></li>
            <% else %>
              <li><%= link_to "Sign up", sign_up_path %></li>
              <li><%= link_to "Log in", log_in_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <ui-view></ui-view>
        </div>
      </div>
    <div class="container-fluid">
      <div class="list-group results">
        <ol ng-repeat="song in songs">
          <li class="list-group-item">
            <a ng-href="#/track/{{song.id}}" ng-click="clearList()">{{song.title}}</a>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="backgroundimageStyling">
	<div class="layer"></div>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Selecta</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav pull-right">
					<% if logged_in? %>
						<li><%= link_to "Log out", log_out_path %></li>
					<% else %>
						<li><%= link_to "Sign up", sign_up_path %></li>
						<li><%= link_to "Log in", log_in_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="loginmodal-container">
					<h1>Selecta Sign up</h1>

					<%= form_for @user do |f| %>
						<% if @user.errors.any? %>
						<div class="errors">
							<h2>Invalid Sign-up Credentials</h2>
							<ul>
								<% for message in @user.errors.full_messages %>
								<li><%= message %></li>
								<% end %>
							</ul>
						</div>
						<% end %>

					<p class="email">
						<%= f.text_field :email, :placeholder => "Email" %>
					</p>
					<p class="password">
						<%= f.password_field :password, :placeholder => "Password" %>
					</p>
					<p class="password_confirmation">
						<%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
					</p>

					<p class="button"><%= f.submit "Sign Up", :class => "login loginmodal-submit"%></p>
					<% end %>

				</div>
			</div>
		</div>
	</div>
</div>